config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing_page'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'activity', to: 'static_pages#activity'
  devise_for :users
  resources :users, only: [:index, :edit, :show, :update]
  resources :courses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :language, :level, :price, presence: true
  validates :description, length: { minimum: 10 }
  validates :short_description, length: { minimum: 5 }
  has_rich_text :description
  belongs_to :user

  scope :three, -> { limit(3) }

  # Shows course object as title
  def to_s
    title
  end

  LEVELS = %w[Beginner Intermediate Advanced].freeze
  def self.levels
    LEVELS
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable,
  :trackable, :confirmable
  has_many :courses
  rolify

  after_create :assign_default_role

  def assign_default_role
    if self.roles.blank?
      self.add_role(:student)
      self.add_role(:teacher)
    end
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController 
  
  before_action :authenticate_user!
  before_action :set_global_variables #, if: :user_signed_in?

  def set_global_variables
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    # if params['search']
    #   @courses = Course.where('title ILIKE ?', "%#{params['search']}%")
    # else
      #@courses = Course.all
      # @q = Course.ransack(params[:q])
      # @courses = @q.result.includes(:user)
    # end
    if current_user.has_role?(:admin)
      @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
      @courses = @ransack_courses.result.includes(:user)
    else
      flash.alert = "You don't have access to this!"
      redirect_to root_path
    end
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :language, :level, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:landing_page]

  def landing_page
    @latest_courses = Course.order(created_at: :desc).three
    @courses = Course.three
  end

  def activity
    @activities = PublicActivity::Activity.all
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :edit]
  
  def index
    # @users = User.order(created_at: :desc)
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash.notice = "User roles updated"
      redirect_to users_path
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit({role_ids: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.card
  .card-header
    .fas.fa-graduation-cap
    = link_to course.title, course
  .card-body
    - if current_page?(course_path(course))
      = course.description
    - elsif current_page?(courses_path)
      = course.short_description
  .card-footer
    .fas.fa-level-up-alt
    = course.level
    \|
    .fas.fa-globe-americas
    = course.language
    \|
    .fas.fa-wallet
    = number_to_currency(course.price, unit: '£')
  .card-footer
    .far.fa-clock
    = course.created_at.strftime('%d %b %Y')
    .row
    .fas.fa-chalkboard-teacher
    = course.user
  .card-footer
    = link_to 'Show', course, class: 'btn btn-outline-info'
    = link_to 'Edit', edit_course_path(course), class: 'btn btn-outline-warning'
    = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description
    = f.error :description
    = f.input :short_description
    = f.input :language, collection: ['English', 'French', 'German', 'Polish']
    = f.input :level, collection: Course.levels
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
.card.mt-4
  .card-header
    %h1 Editing course
  .card-body
    = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h3.text-center.mt-4.mb-4
  Courses
  %span.badge.bg-secondary
    = @courses.count
.row
  .col-2
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| 
      .input-group-sm
        = f.search_field :title_or_short_description_cont, placeholder: 'course', class: 'form-control mb-1'
        = f.search_field :language_cont, placeholder: 'language', class: 'form-control mb-1'
        = f.search_field :price_eq, placeholder: 'price', class: 'form-control mb-1'
        = f.search_field :user_email_cont, placeholder: 'email', class: 'form-control mb-1'
        = f.label :level
        = f.select :level_cont, Course.levels, include_blank: true, class: 'form-select'
        = f.button type: 'submit', class: 'btn btn-sm btn-dark' do
          Search
          .fas.fa-search
    =link_to courses_path, class: 'btn btn-sm btn-info mt-4' do 
      .fas.fa-redo-alt
  .col-10
    .card-columns
      = render partial: 'courses/course', collection: @courses

%br
  

app/views/courses/new.html.haml
.card.mt-4
  .card-header
    %h1 New course
  .card-body
    = render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
%p.mt-2
  = link_to 'Courses', courses_path
  \/
  = link_to @course.title, course_path

= render 'courses/course', course: @course

app/views/layouts/_footer.html.haml
%hr
%footer
  .container.text-center.p-3
    .row 
      .col-md-4
        BareCourses
        &#169
        = Time.now.year
      .col-md-4
        = link_to privacy_policy_path do 
          Privacy Policy
      .col-md-4
        About Us

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light{:style => "background-color: #6c90ad;"}
  .container-fluid
    = link_to root_path, class: 'navbar-brand font-weight-bold font-italic' do
      %h2 BareCourses
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      - if user_signed_in?
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0.mr-auto
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
            = link_to root_path, class: 'nav-link' do
              .fas.fa-home
              Home
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
            = link_to courses_path, class: 'nav-link' do
              .fas.fa-book-open
              Courses
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
            = link_to new_course_path, class: 'nav-link' do
              .fas.fa-plus
              New Course
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
            = link_to users_path, class: 'nav-link' do
              .fas.fa-users
              Users

        %ul.navbar-nav.ml-auto
          = search_form_for @ransack_courses, as: :courses_search, url: courses_path, class: 'form d-flex' do |f|
            .input-group
              = f.search_field :title_or_short_description_cont, class: 'form-control', placeholder: 'Search', type: 'search', 'aria-label' => 'Search'
              = f.button type: 'submit', class: 'btn btn-sm btn-dark' do
                .fas.fa-search
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(activity_path)}"}
            = link_to activity_path, class: 'nav-link' do
              .fas.fa-bell
              Activity
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.email
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              %li
                = link_to 'Edit Account', edit_user_registration_path, class: 'dropdown-item'
              %li
                = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'
      - else
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0.mr-auto
          %li.nav-item
            = link_to 'Login', new_user_session_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Sign up', new_user_registration_path, class: 'nav-link'

app/views/layouts/_notices.html.haml
- flash.each do |type, msg|
  - color = type == 'notice' ? 'success' : 'danger'
  %div{:class => "alert alert-#{color} text-center", :role => "alert"}
    = msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %title CourseApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    = render 'layouts/notices'
    .container
      = yield
    %div{:style => "background-color: #6c90ad;"}
      = render 'layouts/footer'

app/views/static_pages/activity.html.haml
%h3.text-center.mt-4.mb-4
  Activity
  %span.badge.bg-secondary
    = @activities.count

%ul.list-group
  - @activities.each do |a|
    %li.list-group-item
      = a.owner
      = 'did something like'
      = a.key
      = link_to a.trackable, a.trackable

app/views/static_pages/landing_page.html.haml
.jumbotron
  %h2.text-center
    .fas.fa-chalkboard
    \| 
    What do you want to learn today?
    -# = form_with url: courses_path, class: 'form d-flex mt-4', method: :get do |form|
    -#   = form.text_field :search, class: 'form-control me-2', placeholder: "Search", type: "search", 'aria-label' => 'Search'
    -#   = form.submit 'Search', class: 'button btn btn-outline-dark', type: 'submit'
    - if user_signed_in?
      = search_form_for @ransack_courses, as: :courses_search, url: courses_path, class: 'form d-flex mt-4' do |f|
        = f.search_field :title_or_short_description_cont, class: 'form-control', placeholder: 'Find a course', type: 'search', 'aria-label' => 'Search'
        = f.button type: 'submit', class: 'btn btn-dark' do
          .fas.fa-search

.card-group.mb-4
  .card
    .card-body.text-center
      %h1.card-title.fas.fa-graduation-cap
      %p.card-text
        = Course.count
        Online Courses
      %p.card-text
        Find your perfect course and start learning now!
  .card
    .card-body.text-center
      %h1.card-title.fas.fa-user-graduate
      %p.card-text
        = Course.distinct.count 
        teachers ready to teach. Find the perfect instructor for you.
  .card
    .card-body.text-center
      %h1.card-title.fas.fa-user-friends
      %p.card-text
        = User.count
        active users. Join them today and learn a new skill.
  .card
    .card-body.text-center
      %h1.card-title.far.fa-thumbs-up
      %p.card-text
        Get life-time access.
        Learn when you want, in your own time.


%hr
%h2.mb-4 Popular Courses
.card-columns
  = render partial: 'courses/course', collection: @courses
%hr
%h2.mb-4 Top Rated Courses
.card-columns
  = render partial: 'courses/course', collection: @courses
%hr
%h2.mb-4 Most recent courses
.card-columns
  = render partial: 'courses/course', collection: @latest_courses

app/views/static_pages/privacy_policy.html.haml
%h1 StaticPages#privacy_policy
%p Find me in app/views/static_pages/privacy_policy.html.erb
= link_to 'Home', root_path

app/views/users/_user.html.haml
.card
  .card-header
    = user
  .card-body
    Signed up:
    %i{class: 'text-primary'}
      = time_ago_in_words(user.created_at)
      ago
    .row
    Last signed in:
    %i{class: 'text-primary'}
      = time_ago_in_words(user.last_sign_in_at || user.created_at)
      ago
  .card-footer
    Confirmed?
    - if user.confirmed?
      .badge.badge-success yes
    - else
      .badge.badge-danger no
  .card-footer
    - user.roles.each do |role|
      .badge.badge-info= role.name
  .card-footer
    = link_to 'edit', edit_user_path(user), class: 'btn btn-sm btn-outline-secondary'

app/views/users/edit.html.haml
.card.mt-4
  .card-header
    Editing roles for 
    = @user
  .card-body
    = simple_form_for(@user) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
      .form-inputs
        = f.collection_check_boxes :role_ids, Role.all, :id, :name, class: 'form-check-input p-3'
      .form-actions
        = f.button :submit, class: 'btn btn-sm'
  .card-footer 
    = link_to 'Cancel', users_path, class: 'btn btn-sm btn-outline-danger'

app/views/users/index.html.haml
%h3.text-center.mt-4.mb-4
  Users
  %span.badge.bg-secondary
    = User.count

.card-columns
  = render partial: 'users/user', collection: @users

= search_form_for @q do |f|
  .row.g-1
    .col-auto
      = f.search_field :email_cont, placeholder: 'email', class: 'form-control'
    .col-auto
      = f.submit 'Search', class: 'btn btn-outline-info'
=link_to users_path, class: 'btn btn-sm btn-info m-1' do 
  .fas.fa-redo-alt

%table.table.table-striped
  %thead
    %tr
      %th{:scope => "col"}
        =sort_link(@q, :email, 'User')
      %th{:scope => "col"}
        =sort_link(@q, :sign_in_count, 'No. of Sign Ins')
      %th{:scope => "col"} Last Sign In
  %tbody
    - @users.each do |user|
      %tr
        %td=user
        %td=user.sign_in_count
        %td=user.last_sign_in_at